### ISSUE TITLE
Basic Auth Not Working

### ISSUE THREAD

**Issue by anisbhsl** [cornelk/goscrape#20]
While trying to scrape a website that uses basic auth, it is throwing ```401```.

```
auth := base64.StdEncoding.EncodeToString([]byte(s.Config.Username + ":" + s.Config.Password))
s.browser.AddRequestHeader("Authorization", "Basic "+auth)
```
The same website throws ```200``` response when requested using ```Postman```. 

Any ideas why this might not be working?

**Comment by cornelk** [comment]
Does the password contain any special character? Can you print the content of `auth` and verify with an (online) base64 encoder that the data is valid?

**Comment by anisbhsl** [comment]
Yes, I have already tried out printing the password and verified with that given by Postman.

I also tried by placing actual base64 encoded password into the code but didn't succeed either.

**Comment by anisbhsl** [comment]
The password is simple: mixed of alphabet and numbers only.
