### ISSUE TITLE
Can this be used with Chrome/Chromium/Vivaldi/Brave cookies?

### ISSUE THREAD

**Issue by takusuman** [cornelk/goscrape#41]
**Is your feature request related to a problem? Please describe.**
I wish I could download the full online Calculus booklet from my university as a single HTML file, but I would need to log in before, so may I need to pass my cookies to ``goscrape``.

**Describe the solution you'd like**
Well, could we have a way to get Chrome-esque cookies on this program?  
I'm using Vivaldi currently, so I'm willing to test the feature and even help on something if needed --- I'm currently programming in C, but I think I can go to Go (non-intended pun) with little to no effort.

**Describe alternatives you've considered**
I've tried to download it with the [WebScrapBook extension for Chrome](https://github.com/danny0838/webscrapbook), but it kind of breaks the page and still referencing the original URL instead of editing it to match the local, relative path.

**Additional context**
Well, there are also videos on the page that WebScrapBook is incapable of downloading, so I use the [hls downloader extension](https://github.com/puemos/hls-downloader). I think I wouldn't bother downloading videos outside goscrape if needed anyway.

**Comment by takusuman** [comment]
Just an addendum: something that would make me use goscrape over WebScrapBook would be the possibility to run it locally and download the pages in batch instead of one per one.

**Comment by cornelk** [comment]
> Just an addendum to "additional context": something that would make me use goscrape over WebScrapBook would be the possibility to run it locally and download the pages in batch instead of one per one.

Thanks for the feature request, cookie support and a new version will be released tomorrow. For the batching please create a new feature request with a desired usage example

**Comment by takusuman** [comment]
> > Just an addendum to "additional context": something that would make me use goscrape over WebScrapBook would be the possibility to run it locally and download the pages in batch instead of one per one.
> 
> Thanks for the feature request, cookie support and a new version will be released tomorrow. For the batching please create a new feature request with a desired usage example

Well, unless you think it would be cool to have it, I don't think a built-in batch function would be needed right now, since one can use a foreach loop (or the ``apply`` command) for iterating over URLs.
I'm really busy lately, but I will try to sketch something like a built-in batch function that reads from a text file if you guys are willing to.

**Comment by takusuman** [comment]
By the way, it would be great if a list of embed streams (video and/or audio) could be generated and kept as a .txt indicating which name can one download locally to replace in the backup. @cornelk

**Comment by cornelk** [comment]
> By the way, it would be great if a list of embed streams (video and/or audio) could be generated and kept as a .txt indicating which name can one download locally to replace in the backup. @cornelk

one issues per feature/bug report please otherwise this will get lost the moment this issue will be closed

**Comment by takusuman** [comment]
> one issues per feature/bug report please otherwise this will get lost the moment this issue will be closed

Sure, I will be opening it right now.
